### ISSUE TITLE
Custom command not working: an error occured: p not supplied

### ISSUE THREAD

**Issue by gubraun** [blackducksoftware/synopsys-coverity-azure-devops#6]
When I try to use custom commands, I always get an error 'p not supplied'. There are no further logs to diagnose the problem
```
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-vm'
    projectName: 'Azure Hello World'
    streamName: 'az-hello-world'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    coverityRunType: 'custom'
    customCoverityCommands: 'cov-analyze --ident'
    allowUntrusted: true
```
```
2020-03-30T15:21:45.9592471Z ##[section]Starting: synopsys***
2020-03-30T15:21:45.9603540Z ==============================================================================
2020-03-30T15:21:45.9604030Z Task         : Synopsys Coverity
2020-03-30T15:21:45.9604473Z Description  : The Azure Dev Ops plugin for Synopsys Coverity.
2020-03-30T15:21:45.9604878Z Version      : 1.0.7
2020-03-30T15:21:45.9605170Z Author       : Synopsys
2020-03-30T15:21:45.9605520Z Help         : 
2020-03-30T15:21:45.9605926Z ==============================================================================
2020-03-30T15:21:46.4545472Z Starting Coverity for ADO.
2020-03-30T15:21:46.4546432Z Finding Coverity bin.
2020-03-30T15:21:46.4547488Z Getting COVERITY_TOOL_HOME from the environment.
2020-03-30T15:21:46.4549329Z Found: /mnt/***store/cov-analysis-share/cov-analysis
2020-03-30T15:21:46.7692556Z Exists: true
2020-03-30T15:21:46.9864685Z Version Files Exists: true
2020-03-30T15:21:47.1809167Z Coverity Version: 2019.12
2020-03-30T15:21:47.2892200Z Bin exists: true
2020-03-30T15:21:47.2892633Z Coverity succesfully found.
2020-03-30T15:21:47.2902464Z Reading ADO inputs.
2020-03-30T15:21:47.2909860Z Reading *** service input.
2020-03-30T15:21:47.2983443Z Determining build and issue inputs.
2020-03-30T15:21:47.2983986Z Parsing command inputs.
2020-03-30T15:21:47.2984325Z Parsing custom command inputs.
2020-03-30T15:21:47.2986281Z Parsed command with tool 'cov-analyze' and custom args of length 1
2020-03-30T15:21:47.2987623Z Verifying ADO inputs.
2020-03-30T15:21:47.2991986Z Testing connection over soap.
2020-03-30T15:21:47.8005960Z Connected!
2020-03-30T15:21:47.8006504Z Testing connection over rest.
2020-03-30T15:21:47.8012910Z Connected!
2020-03-30T15:21:47.8014846Z Finding project and stream.
2020-03-30T15:21:48.0374038Z Found project.
2020-03-30T15:21:48.0377329Z Found stream.
2020-03-30T15:21:48.0377697Z Project: Azure Hello World
2020-03-30T15:21:48.0378597Z Stream: az-hello-world
2020-03-30T15:21:48.0378908Z Succesfully found project and stream.
2020-03-30T15:21:48.0381228Z Using working directory: undefined
2020-03-30T15:21:48.0381610Z Using intermediate directory: undefined
2020-03-30T15:21:48.0382731Z Setting up the environment for *** commands.
2020-03-30T15:21:48.0393679Z Updated the following environment variables: PATH+COVERITYTOOLBIN,COV_USER,COVERITY_PASSPHRASE,COV_URL,COV_PROJECT,COV_STREAM,COV_VIEW,COV_DIR
2020-03-30T15:21:48.0397544Z Will run (1) *** commands.
2020-03-30T15:21:48.0399835Z Substituting (1) arguments with *** variables if applicable.
2020-03-30T15:21:48.0416226Z Running *** command.
2020-03-30T15:21:48.0419735Z Searching for *** tool: cov-analyze
2020-03-30T15:21:48.3711054Z Found tool: /mnt/***store/cov-analysis-share/cov-analysis/bin/cov-analyze
2020-03-30T15:21:48.3717573Z Building coverty command: /mnt/***store/cov-analysis-share/cov-analysis/bin/cov-analyze
2020-03-30T15:21:48.5816632Z An error occured: p not supplied
2020-03-30T15:21:48.5867745Z ##[error]p not supplied
2020-03-30T15:21:48.5902401Z ##[section]Finishing: synopsys***
```

**Comment by asbiin** [comment]
I had the same issue, and I made #2 (but Synopsys does not seems to maintain this repo? ...)

**Comment by asbiin** [comment]
This is fixed by #2 and can be closed

**Comment by TMattes** [comment]
This issue still persists in version 1.0.0.11, so how do we get the fix?
